/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappMarketingServiceRouteImport } from './routes/whatsapp-marketing-service'
import { Route as WhatsappApiRouteImport } from './routes/whatsapp-api'
import { Route as VoiceServicesRouteImport } from './routes/voice-services'
import { Route as TwoWayMessagingRouteImport } from './routes/two-way-messaging'
import { Route as SmppRouteImport } from './routes/smpp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RcsBusinessMessagingRouteImport } from './routes/rcs-business-messaging'
import { Route as OtpSolutionsRouteImport } from './routes/otp-solutions'
import { Route as InternationalMessagingRouteImport } from './routes/international-messaging'
import { Route as HlrLookupRouteImport } from './routes/hlr-lookup'
import { Route as EmailServicesRouteImport } from './routes/email-services'
import { Route as DatabaseCampaignsRouteImport } from './routes/database-campaigns'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatbotsRouteImport } from './routes/chatbots'
import { Route as AnntelMessagingRouteImport } from './routes/anntel-messaging'
import { Route as AnntelDigitalRouteImport } from './routes/anntel-digital'
import { Route as AdminResellerRouteImport } from './routes/admin-reseller'
import { Route as IndexRouteImport } from './routes/index'

const WhatsappMarketingServiceRoute =
  WhatsappMarketingServiceRouteImport.update({
    id: '/whatsapp-marketing-service',
    path: '/whatsapp-marketing-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const WhatsappApiRoute = WhatsappApiRouteImport.update({
  id: '/whatsapp-api',
  path: '/whatsapp-api',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceServicesRoute = VoiceServicesRouteImport.update({
  id: '/voice-services',
  path: '/voice-services',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoWayMessagingRoute = TwoWayMessagingRouteImport.update({
  id: '/two-way-messaging',
  path: '/two-way-messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const SmppRoute = SmppRouteImport.update({
  id: '/smpp',
  path: '/smpp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RcsBusinessMessagingRoute = RcsBusinessMessagingRouteImport.update({
  id: '/rcs-business-messaging',
  path: '/rcs-business-messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpSolutionsRoute = OtpSolutionsRouteImport.update({
  id: '/otp-solutions',
  path: '/otp-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalMessagingRoute = InternationalMessagingRouteImport.update({
  id: '/international-messaging',
  path: '/international-messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const HlrLookupRoute = HlrLookupRouteImport.update({
  id: '/hlr-lookup',
  path: '/hlr-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailServicesRoute = EmailServicesRouteImport.update({
  id: '/email-services',
  path: '/email-services',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseCampaignsRoute = DatabaseCampaignsRouteImport.update({
  id: '/database-campaigns',
  path: '/database-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotsRoute = ChatbotsRouteImport.update({
  id: '/chatbots',
  path: '/chatbots',
  getParentRoute: () => rootRouteImport,
} as any)
const AnntelMessagingRoute = AnntelMessagingRouteImport.update({
  id: '/anntel-messaging',
  path: '/anntel-messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const AnntelDigitalRoute = AnntelDigitalRouteImport.update({
  id: '/anntel-digital',
  path: '/anntel-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResellerRoute = AdminResellerRouteImport.update({
  id: '/admin-reseller',
  path: '/admin-reseller',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-reseller': typeof AdminResellerRoute
  '/anntel-digital': typeof AnntelDigitalRoute
  '/anntel-messaging': typeof AnntelMessagingRoute
  '/chatbots': typeof ChatbotsRoute
  '/contact': typeof ContactRoute
  '/database-campaigns': typeof DatabaseCampaignsRoute
  '/email-services': typeof EmailServicesRoute
  '/hlr-lookup': typeof HlrLookupRoute
  '/international-messaging': typeof InternationalMessagingRoute
  '/otp-solutions': typeof OtpSolutionsRoute
  '/rcs-business-messaging': typeof RcsBusinessMessagingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smpp': typeof SmppRoute
  '/two-way-messaging': typeof TwoWayMessagingRoute
  '/voice-services': typeof VoiceServicesRoute
  '/whatsapp-api': typeof WhatsappApiRoute
  '/whatsapp-marketing-service': typeof WhatsappMarketingServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-reseller': typeof AdminResellerRoute
  '/anntel-digital': typeof AnntelDigitalRoute
  '/anntel-messaging': typeof AnntelMessagingRoute
  '/chatbots': typeof ChatbotsRoute
  '/contact': typeof ContactRoute
  '/database-campaigns': typeof DatabaseCampaignsRoute
  '/email-services': typeof EmailServicesRoute
  '/hlr-lookup': typeof HlrLookupRoute
  '/international-messaging': typeof InternationalMessagingRoute
  '/otp-solutions': typeof OtpSolutionsRoute
  '/rcs-business-messaging': typeof RcsBusinessMessagingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smpp': typeof SmppRoute
  '/two-way-messaging': typeof TwoWayMessagingRoute
  '/voice-services': typeof VoiceServicesRoute
  '/whatsapp-api': typeof WhatsappApiRoute
  '/whatsapp-marketing-service': typeof WhatsappMarketingServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-reseller': typeof AdminResellerRoute
  '/anntel-digital': typeof AnntelDigitalRoute
  '/anntel-messaging': typeof AnntelMessagingRoute
  '/chatbots': typeof ChatbotsRoute
  '/contact': typeof ContactRoute
  '/database-campaigns': typeof DatabaseCampaignsRoute
  '/email-services': typeof EmailServicesRoute
  '/hlr-lookup': typeof HlrLookupRoute
  '/international-messaging': typeof InternationalMessagingRoute
  '/otp-solutions': typeof OtpSolutionsRoute
  '/rcs-business-messaging': typeof RcsBusinessMessagingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smpp': typeof SmppRoute
  '/two-way-messaging': typeof TwoWayMessagingRoute
  '/voice-services': typeof VoiceServicesRoute
  '/whatsapp-api': typeof WhatsappApiRoute
  '/whatsapp-marketing-service': typeof WhatsappMarketingServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-reseller'
    | '/anntel-digital'
    | '/anntel-messaging'
    | '/chatbots'
    | '/contact'
    | '/database-campaigns'
    | '/email-services'
    | '/hlr-lookup'
    | '/international-messaging'
    | '/otp-solutions'
    | '/rcs-business-messaging'
    | '/sitemap.xml'
    | '/smpp'
    | '/two-way-messaging'
    | '/voice-services'
    | '/whatsapp-api'
    | '/whatsapp-marketing-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-reseller'
    | '/anntel-digital'
    | '/anntel-messaging'
    | '/chatbots'
    | '/contact'
    | '/database-campaigns'
    | '/email-services'
    | '/hlr-lookup'
    | '/international-messaging'
    | '/otp-solutions'
    | '/rcs-business-messaging'
    | '/sitemap.xml'
    | '/smpp'
    | '/two-way-messaging'
    | '/voice-services'
    | '/whatsapp-api'
    | '/whatsapp-marketing-service'
  id:
    | '__root__'
    | '/'
    | '/admin-reseller'
    | '/anntel-digital'
    | '/anntel-messaging'
    | '/chatbots'
    | '/contact'
    | '/database-campaigns'
    | '/email-services'
    | '/hlr-lookup'
    | '/international-messaging'
    | '/otp-solutions'
    | '/rcs-business-messaging'
    | '/sitemap.xml'
    | '/smpp'
    | '/two-way-messaging'
    | '/voice-services'
    | '/whatsapp-api'
    | '/whatsapp-marketing-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminResellerRoute: typeof AdminResellerRoute
  AnntelDigitalRoute: typeof AnntelDigitalRoute
  AnntelMessagingRoute: typeof AnntelMessagingRoute
  ChatbotsRoute: typeof ChatbotsRoute
  ContactRoute: typeof ContactRoute
  DatabaseCampaignsRoute: typeof DatabaseCampaignsRoute
  EmailServicesRoute: typeof EmailServicesRoute
  HlrLookupRoute: typeof HlrLookupRoute
  InternationalMessagingRoute: typeof InternationalMessagingRoute
  OtpSolutionsRoute: typeof OtpSolutionsRoute
  RcsBusinessMessagingRoute: typeof RcsBusinessMessagingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmppRoute: typeof SmppRoute
  TwoWayMessagingRoute: typeof TwoWayMessagingRoute
  VoiceServicesRoute: typeof VoiceServicesRoute
  WhatsappApiRoute: typeof WhatsappApiRoute
  WhatsappMarketingServiceRoute: typeof WhatsappMarketingServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-marketing-service': {
      id: '/whatsapp-marketing-service'
      path: '/whatsapp-marketing-service'
      fullPath: '/whatsapp-marketing-service'
      preLoaderRoute: typeof WhatsappMarketingServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-api': {
      id: '/whatsapp-api'
      path: '/whatsapp-api'
      fullPath: '/whatsapp-api'
      preLoaderRoute: typeof WhatsappApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-services': {
      id: '/voice-services'
      path: '/voice-services'
      fullPath: '/voice-services'
      preLoaderRoute: typeof VoiceServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-way-messaging': {
      id: '/two-way-messaging'
      path: '/two-way-messaging'
      fullPath: '/two-way-messaging'
      preLoaderRoute: typeof TwoWayMessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smpp': {
      id: '/smpp'
      path: '/smpp'
      fullPath: '/smpp'
      preLoaderRoute: typeof SmppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rcs-business-messaging': {
      id: '/rcs-business-messaging'
      path: '/rcs-business-messaging'
      fullPath: '/rcs-business-messaging'
      preLoaderRoute: typeof RcsBusinessMessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp-solutions': {
      id: '/otp-solutions'
      path: '/otp-solutions'
      fullPath: '/otp-solutions'
      preLoaderRoute: typeof OtpSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-messaging': {
      id: '/international-messaging'
      path: '/international-messaging'
      fullPath: '/international-messaging'
      preLoaderRoute: typeof InternationalMessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hlr-lookup': {
      id: '/hlr-lookup'
      path: '/hlr-lookup'
      fullPath: '/hlr-lookup'
      preLoaderRoute: typeof HlrLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-services': {
      id: '/email-services'
      path: '/email-services'
      fullPath: '/email-services'
      preLoaderRoute: typeof EmailServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database-campaigns': {
      id: '/database-campaigns'
      path: '/database-campaigns'
      fullPath: '/database-campaigns'
      preLoaderRoute: typeof DatabaseCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbots': {
      id: '/chatbots'
      path: '/chatbots'
      fullPath: '/chatbots'
      preLoaderRoute: typeof ChatbotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anntel-messaging': {
      id: '/anntel-messaging'
      path: '/anntel-messaging'
      fullPath: '/anntel-messaging'
      preLoaderRoute: typeof AnntelMessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anntel-digital': {
      id: '/anntel-digital'
      path: '/anntel-digital'
      fullPath: '/anntel-digital'
      preLoaderRoute: typeof AnntelDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reseller': {
      id: '/admin-reseller'
      path: '/admin-reseller'
      fullPath: '/admin-reseller'
      preLoaderRoute: typeof AdminResellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminResellerRoute: AdminResellerRoute,
  AnntelDigitalRoute: AnntelDigitalRoute,
  AnntelMessagingRoute: AnntelMessagingRoute,
  ChatbotsRoute: ChatbotsRoute,
  ContactRoute: ContactRoute,
  DatabaseCampaignsRoute: DatabaseCampaignsRoute,
  EmailServicesRoute: EmailServicesRoute,
  HlrLookupRoute: HlrLookupRoute,
  InternationalMessagingRoute: InternationalMessagingRoute,
  OtpSolutionsRoute: OtpSolutionsRoute,
  RcsBusinessMessagingRoute: RcsBusinessMessagingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmppRoute: SmppRoute,
  TwoWayMessagingRoute: TwoWayMessagingRoute,
  VoiceServicesRoute: VoiceServicesRoute,
  WhatsappApiRoute: WhatsappApiRoute,
  WhatsappMarketingServiceRoute: WhatsappMarketingServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
